healthcheck:
  enabled: true

wireguard:
  peerDns: auto
  showConfigs: "true"

configFiles:
  wg1.conf: |
    [Interface]
    Address = 10.201.0.1
    ListenPort = 51820
    PrivateKey = abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOP0=
    PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth+ -j MASQUERADE
    PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth+ -j MASQUERADE

    [Peer]
    PublicKey = ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnop0=
    AllowedIPs = 10.201.0.0/24

probeInterface: wg1

service:
  type: ClusterIP
