apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wireguard.fullname" . }}
  labels:
    {{- include "wireguard.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "wireguard.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "wireguard.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "wireguard.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: wireguard
              containerPort: {{ .Values.service.port }}
              protocol: UDP
          env:
            - name: ALLOWEDIPS
              value: {{ .Values.wireguard.accessibleIps }}
            - name: LOG_CONFS
              value: {{ .Values.wireguard.showConfigs | quote }}
            - name: PEERS
              value: {{ .Values.wireguard.clientPeers }}
            {{- with .Values.wireguard.peerDns }}
            - name: PEERDNS
              value: {{ . }}
            {{- end }}
            - name: TZ
              value: {{ .Values.wireguard.timeZone }}
          livenessProbe:
            exec:
              command:
                - ip
                - link
                - show
                - {{ .Values.probeInterface }}
                - up
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            exec:
              command:
                - ip
                - link
                - show
                - {{ .Values.probeInterface }}
                - up
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if or .Values.persistence.enabled .Values.configFiles }}
          volumeMounts:
          {{- end }}
          {{- if .Values.persistence.enabled }}
            - name: wireguard-peers-config
              mountPath: /config/
          {{- end }}
          {{- if .Values.configFiles }}
            - name: etc-wireguard
              mountPath: /etc/wireguard/
              # readOnly: true
          {{- end }}
        {{- if .Values.healthcheck.enabled }}
        - name: httphealth
          image: {{ .Values.healthcheck.image.repository }}:{{ .Values.healthcheck.image.tag }}
          imagePullPolicy: {{ .Values.healthcheck.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 58000
              protocol: TCP
          command:
            - /usr/local/bin/healthcheck
            - {{ .Values.probeInterface }}
          volumeMounts:
            - name: wireguard-healthcheck
              mountPath: /usr/local/bin/healthcheck
              subPath: healthcheck.py
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- if .Values.persistence.enabled }}
        - name: wireguard-peers-config
          persistentVolumeClaim:
          {{- if .Values.persistence.existingClaim }}
            claimName: {{ .Values.persistence.existingClaim }}
          {{- else }}
            claimName: {{ include "wireguard.fullname" . }}
          {{- end }}
      {{- end }}
      {{- if .Values.healthcheck.enabled }}
        - name: wireguard-healthcheck
          configMap:
            name: {{ include "wireguard.fullname" . }}-healthcheck
            defaultMode: 0755
            items:
            - key: healthcheck.py
              path: healthcheck.py
      {{- end }}
      {{- if .Values.configFiles }}
        - name: etc-wireguard
          secret:
            secretName: {{ include "wireguard.fullname" . }}
      {{- end }}
