{{- if .Values.configFiles }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wireguard.fullname" . }}
  labels:
    {{- include "wireguard.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.configFiles }}
  {{ $k }}: {{ $v | b64enc }}
  {{- end }}
{{- end }}
