apiVersion: v1
kind: Service
metadata:
  name: {{ include "wireguard.fullname" . }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "wireguard.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 51820
      protocol: UDP
      name: wireguard
    - port: {{ .Values.service.healthHttpPort }}
      targetPort: 58000
      protocol: TCP
      name: http
  selector:
    {{- include "wireguard.selectorLabels" . | nindent 4 }}
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
